### ISSUE TITLE
Drupal 8 coding standards

### ISSUE THREAD

**Issue by therealssj** [paraacha/pubkey_encrypt#1]
Just a few coding standard issues phpcs pointed. 
This is just a reminder so that they don't get carried on in future updates.

**Files in src/Annotation folder**
Namespaced classes, traits and interfaces should not begin with a file doc comment

**Files in src/Form folder**
Namespaced classes, traits and interfaces should not begin with a file doc comment

**Files in src/Plugin folder and KeyProvider subfolder**
Namespaced classes, traits and interfaces should not begin with a file doc comment

**src/PubkeyEncryptManager.php**
Namespaced classes, traits and interfaces should not begin with a file doc comment
Also a lot of functions in this class seem to be missing arguments in the doc block

**src/Plugin/AsymmetricKeysGeneratorInterface.php**
Multiple doc blocks with Description for return value missing

**src/Plugin/LoginCredentialsProviderInterface**
Multiple doc blocks with Description for return value missing

**Comment by paraacha** [comment]
Thanks for pointing them out. Will refactor the module as per these.

**Comment by therealssj** [comment]
**src/Controller/PubkeyEncryptOverviewController** 
Missing the doc block for the second argument `ConfigFactoryInterface $config_factory`

**Comment by paraacha** [comment]
Done with removing @file doc blocks from all namespaced classes.  I've deliberately not provided arguments in doc blocks for functions with simple enough descriptions & parameters.
