### ISSUE TITLE
PubkeyEncryptSubscriber property not declared.

### ISSUE THREAD

**Issue by therealssj** [paraacha/pubkey_encrypt#3]
This event subscriber has the pubkeyEncryptManager variable which stores the instance of PubkeyEncryptManager class but the variable has not been defined anywhere.

**Comment by therealssj** [comment]
```
  /**
   * Pubkey Encrypt manager service.
   *
   * @var \Drupal\pubkey_encrypt\PubkeyEncryptManager
   */
  protected $pubkeyEncryptManager;
```

**Comment by paraacha** [comment]
Thank you for the patch and issue. Done.
